# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 567766133155b58c88df0f23ae67e3f4e9d35f78081be3beaade9c04eccd62896dff72d13ad6c65d236cbbf4321f2487f6f6f13a33c6fd3204cf53d259ab8f6d

test:
  secret_key_base: d21c1ad90a472055be40d0945c4682b32b13c09c28aa2243279d1bb9d9adaa35810e607b5275d262866c75dffb3ab56af6dfb29ecda3288bab7c163d7a2200a4

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
